// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUw9YCi3PsZlpusUyo-8PYEDi-KWaJE9A',
    appId: '1:787776350069:web:1e32e62f8db279fcebd53c',
    messagingSenderId: '787776350069',
    projectId: 'flutter-chat-6d0ba',
    authDomain: 'flutter-chat-6d0ba.firebaseapp.com',
    storageBucket: 'flutter-chat-6d0ba.appspot.com',
    measurementId: 'G-9PS8SMJLFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ODNJ4KfKDe6FvyS-OvajO9Q0yfqY57k',
    appId: '1:787776350069:android:98346862f4bfdacdebd53c',
    messagingSenderId: '787776350069',
    projectId: 'flutter-chat-6d0ba',
    storageBucket: 'flutter-chat-6d0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDbMFXwtEQtkiV9Jbv1sWGe4mAxG9mzVI',
    appId: '1:787776350069:ios:6bd20397b8a46109ebd53c',
    messagingSenderId: '787776350069',
    projectId: 'flutter-chat-6d0ba',
    storageBucket: 'flutter-chat-6d0ba.appspot.com',
    androidClientId: '787776350069-ton28lep53k0kj0uac1og2p6mv8s2587.apps.googleusercontent.com',
    iosClientId: '787776350069-qvnk1sbaps1saaiat99asph9dj8fme8n.apps.googleusercontent.com',
    iosBundleId: 'sharan.flutterChatApp',
  );
}
