name: UAT build generation for release branch

on:
  workflow_dispatch:
    inputs:
      android:
        description: 'Build android build flag'
        required: false
        type: boolean
        default: false
      iOS:
        description: 'Build iOS build flag'
        required: false
        type: boolean
        default: false
      environment:
        description: 'Environment to run tests against'
        type: choice
        required: true
        options:
          - uat
          - prod

jobs:
  build_apk_upload_artifacts:
#    needs: [ build_IOS ]
    name: Build android UAT builds
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#incomingwwebhook'
          message: New build has been deployed
        if: always()