name: UAT build generation for release branch

on:
  repository_dispatch:
    types:
      - configuration-check

jobs:
  build_apk_upload_artifacts:
#    needs: [ build_IOS ]
    name: Build android UAT builds
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#incomingwwebhook'
          message: New build has been deployed
        if: always()