name: UAT build generation for release branch

on:
  push:
    branches: [ github_action_testing ]

jobs:
  build:
    name: Build android UAT builds
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build apk --release
      - name: Create Android apk github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/*.apk
          token: ${{secrets.TOKEN}}
          tag: v1.0.${{ github.run_number }}
          allowUpdates: true
          artifactContentType: "raw"
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#incomingwwebhook'
          message: New build has been deployed
        if: always()